# Generated by Django 2.2 on 2019-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
