# Generated by Django 2.2 on 2019-04-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0002_urlshortener_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
