# Generated by Django 2.2 on 2019-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0004_auto_20190406_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
