# Generated by Django 2.2 on 2019-04-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0005_auto_20190406_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
